Repository Corona-Studio/ProjBobcat, pull requests merged in 2024-03, with the labels that each got.

#125 [BugFix & Improvements] add support for legacy game natives replacement
  ProjBobcat/ProjBobcat/Class/Helper/AuthPropertyHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/EncodingHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/GameResourcesResolveHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/GameVersionHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/NativeReplace/NativeReplaceHelper.Json.cs
  ProjBobcat/ProjBobcat/Class/Helper/NativeReplace/NativeReplaceHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/RulesHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/TOMLParser/TommyExtensions.cs
  ProjBobcat/ProjBobcat/Class/LaunchWrapper.cs
  ProjBobcat/ProjBobcat/Class/Model/JsonContexts/JsonElementContext.cs
  ProjBobcat/ProjBobcat/Class/Model/JsonContexts/NativeReplaceModelContext.cs
  ProjBobcat/ProjBobcat/Class/Model/LauncherAccount/LauncherAccountModel.cs
  ProjBobcat/ProjBobcat/Class/Model/LauncherProfile/LauncherProfileModel.cs
  ProjBobcat/ProjBobcat/Class/Model/NativeReplaceModel.cs
  ProjBobcat/ProjBobcat/Class/Model/NativeReplacementPolicy.cs
  ProjBobcat/ProjBobcat/DefaultComponent/Launch/DefaultVersionLocator.cs
  ProjBobcat/ProjBobcat/DefaultComponent/Launch/GameCore/DefaultGameCore.cs
  ProjBobcat/ProjBobcat/DefaultComponent/LogAnalysis/DefaultLogAnalyzer.cs
  ProjBobcat/ProjBobcat/DefaultComponent/ResourceInfoResolver/AssetInfoResolver.cs
  ProjBobcat/ProjBobcat/DefaultComponent/ResourceInfoResolver/LibraryInfoResolver.cs
  ProjBobcat/ProjBobcat/Event/GameLogEventArgs.cs
  ProjBobcat/ProjBobcat/Platforms/Windows/DefaultMinecraftUWPCore.cs
Labels: 漏洞 Bug, 新功能 enhancement

#126 fix log encoding detect
  ProjBobcat/ProjBobcat/Class/Helper/EncodingHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/GameResourcesResolveHelper.cs
  ProjBobcat/ProjBobcat/Class/Helper/GameVersionHelper.cs
  ProjBobcat/ProjBobcat/Class/Model/RawVersionModel.cs
  ProjBobcat/ProjBobcat/DefaultComponent/LogAnalysis/DefaultLogAnalyzer.cs
Labels: 漏洞 Bug

#124 Add Unit Test Project
  ProjBobcat/.editorconfig
  ProjBobcat/ProjBobcat.Tests/ClassOrientedTests/JsonConverter/DateTimeConverterUsingDateTimeParseTests.cs
  ProjBobcat/ProjBobcat.Tests/ProjBobcat.Tests.csproj
  ProjBobcat/ProjBobcat.sln
Labels: 开发中 work in progress

#136 Fix LegacyForgeInstallProfile.cs
  ProjBobcat/ProjBobcat/Class/Model/Forge/LegacyForgeInstallProfile.cs
Labels: 漏洞 Bug

#137 Update ProjBobcat.csproj
  ProjBobcat/ProjBobcat/DefaultComponent/Launch/DefaultVersionLocator.cs
  ProjBobcat/ProjBobcat/ProjBobcat.csproj
Labels: 新功能/改进 enhancement
